version: 2
jobs:
  main:
    docker:
      - image: circleci/node:10

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: npm ci

      - run:
          name: Prepare credentials
          command: |
            echo $GOOGLE_APPLICATION_CREDENTIALS_JSON > /home/circleci/project/credentials.json

      - run:
          name: Run tests
          environment:
            GOOGLE_APPLICATION_CREDENTIALS: /home/circleci/project/credentials.json
          command: npm run mocha

  lint:
    docker:
      - image: circleci/node:10

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: npm ci

      - run:
          name: Check lint
          command: npm run lint

  format:
    docker:
      - image: circleci/node:10

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: npm ci

      - run:
          name: Check lint
          command: npm run lint

      - run:
          name: Check prettier
          command: npm run prettier

workflows:
  version: 2

  on-commit:
    jobs:
      - main
      - lint
      - format

  daily:
    triggers:
      - schedule:
          cron: '0 17 * * *'
          filters:
            branches:
              only: master
    jobs:
      - main
      - lint
      - format
